import { Injectable } from '@nestjs/common';

@Injectable()
export class ScorecardRendererService {
  render(application: any): string {
    const dc          = application.decisionCard ?? {};
    const gapDetail   = dc.gapDetail ?? {};
    const gaps        = gapDetail.gaps ?? [];
    const probeGaps   = gaps.filter((g: any) =>
      ['SIGNIFICANT', 'DEALBREAKER'].includes(g.severity) && g.probeQuestion);
    const verdictColor = dc.verdict === 'PROCEED' ? '#22c55e'
                       : dc.verdict === 'REJECT'  ? '#ef4444' : '#f59e0b';

    return `<!DOCTYPE html><html lang="en"><head>
<meta charset="UTF-8">
<title>Scorecard — ${application.application?.job?.title ?? 'Job'} — ${application.application?.candidate?.name ?? 'Candidate'}</title>
<style>
  body { font-family: -apple-system, sans-serif; font-size: 14px; color: #1a1a1a; background: #fff; padding: 40px; max-width: 860px; margin: 0 auto; }
  .verdict-block { display: flex; align-items: center; gap: 16px; padding: 16px 20px; border-radius: 8px; border: 2px solid ${verdictColor}44; background: ${verdictColor}0d; margin-bottom: 24px; }
  .verdict-badge { font-size: 18px; font-weight: 800; color: ${verdictColor}; }
  .two-col { display: grid; grid-template-columns: 1fr 1fr; gap: 16px; margin-bottom: 16px; }
  .section { background: #f9f9f9; border: 1px solid #e5e5e5; border-radius: 6px; padding: 14px; margin-bottom: 12px; }
  h3 { font-size: 12px; font-weight: 600; text-transform: uppercase; letter-spacing: .06em; color: #444; margin: 24px 0 10px; }
  ul { list-style: none; padding: 0; }
  li { padding: 3px 0 3px 14px; font-size: 13px; color: #333; position: relative; }
  li::before { content: '·'; position: absolute; left: 0; color: #999; }
  .probe-q { padding: 8px 12px; background: #fff7ed; border-left: 3px solid #f59e0b; margin-bottom: 8px; font-size: 13px; }
  .tech-chip { font-size: 11px; padding: 2px 8px; border-radius: 12px; }
  .tech-match { background: #dcfce7; color: #166534; }
  .tech-miss  { background: #fee2e2; color: #991b1b; }
  @media print { .no-print { display: none; } @page { margin: 1.5cm; } }
</style></head><body>
<div class="no-print" style="text-align: right; margin-bottom: 20px;">
  <button onclick="window.print()" style="background:#000;color:#fff;border:none;padding:8px 16px;border-radius:4px;cursor:pointer;font-weight:600">Print / Save as PDF</button>
</div>
<h1>${application.application?.job?.title ?? 'Role'} — Candidate Scorecard</h1>
<h2 style="font-size:12px;color:#666;text-transform:uppercase;letter-spacing:.06em;margin-bottom:24px">
  ${application.application?.candidate?.name ?? 'Candidate'} · Generated ${new Date().toLocaleDateString('en-GB',{day:'numeric',month:'long',year:'numeric'})}</h2>

<div class="verdict-block">
  <div class="verdict-badge">${dc.verdict ?? '—'}</div>
  <div>${dc.hrSummary ?? 'No summary available.'}</div>
</div>

<div class="two-col">
  <div class="section"><h3>Strengths</h3><ul>${(dc.strengths??[]).map((s:string)=>`<li>${s}</li>`).join('')||'<li style="color:#999">None recorded</li>'}</ul></div>
  <div class="section"><h3>Risks</h3><ul>${(dc.risks??[]).map((r:string)=>`<li>${r}</li>`).join('')||'<li style="color:#999">None recorded</li>'}</ul></div>
</div>

<h3>Technology Match</h3>
<div class="two-col">
  <div class="section">
    <strong style="font-size:11px;color:#166534">Matched</strong>
    <div style="display:flex;gap:8px;flex-wrap:wrap;margin-top:6px">
      ${(gapDetail.matchedTechnologies??[]).map((t:string)=>`<span class="tech-chip tech-match">${t}</span>`).join('')||'<span style="font-size:12px;color:#999">None</span>'}
    </div>
  </div>
  <div class="section">
    <strong style="font-size:11px;color:#991b1b">Missing</strong>
    <div style="display:flex;gap:8px;flex-wrap:wrap;margin-top:6px">
      ${(gapDetail.missingTechnologies??[]).map((t:string)=>`<span class="tech-chip tech-miss">${t}</span>`).join('')||'<span style="font-size:12px;color:#999">None</span>'}
    </div>
  </div>
</div>

${probeGaps.length > 0 ? `<h3>Probe Questions</h3>${probeGaps.map((g:any)=>`<div class="probe-q"><div style="font-size:10px;font-weight:600;text-transform:uppercase;color:#92400e;margin-bottom:4px">${g.dimension} · ${g.severity}</div>${g.probeQuestion}</div>`).join('')}` : ''}

${dc.reputationNote ? `<div class="section" style="margin-top:12px"><h3>Reputation Note</h3><p style="font-size:13px">${dc.reputationNote}</p></div>` : ''}

<div class="section" style="margin-top:12px"><h3>Not Observable via GitHub</h3>
  <p style="font-size:12px;color:#666">Communication quality · System design thinking · Management capability · Cultural fit · Interview performance — these require interview assessment.</p>
</div>
<div style="font-size:11px;color:#999;text-align:center;padding-top:20px;border-top:1px solid #e5e5e5;margin-top:32px">
  Generated by Colosseum — proof-of-talent hiring platform · ${new Date().toISOString()}
</div>
</body></html>`;
  }
}
