import { Job, Candidate, WalletData, Interview } from "./types";

export const MOCK_JOBS: Job[] = [
  {
    id: "job-1",
    title: "Senior Frontend Engineer",
    department: "Engineering",
    location_type: "remote",
    description: "Build the next generation of our hiring platform UI.",
    skills: ["React", "TypeScript", "Tailwind CSS"],
    status: "active",
    bond_status: "staked",
    bond_amount: 2400,
    applicant_count: 47,
    created_at: "2026-04-01T10:00:00Z",
    published_at: "2026-04-02T09:00:00Z",
    closed_at: null,
  },
  {
    id: "job-2",
    title: "Solidity Smart Contract Engineer",
    department: "Blockchain",
    location_type: "remote",
    description: "Design and audit our escrow bond contracts.",
    skills: ["Solidity", "Foundry", "EVM"],
    status: "active",
    bond_status: "staked",
    bond_amount: 3200,
    applicant_count: 23,
    created_at: "2026-04-05T10:00:00Z",
    published_at: "2026-04-06T09:00:00Z",
    closed_at: null,
  },
  {
    id: "job-3",
    title: "Product Designer",
    department: "Design",
    location_type: "hybrid",
    description: "Lead design for our employer and candidate dashboards.",
    skills: ["Figma", "Design Systems", "User Research"],
    status: "draft",
    bond_status: "pending",
    bond_amount: 1800,
    applicant_count: 0,
    created_at: "2026-04-10T10:00:00Z",
    published_at: null,
    closed_at: null,
  },
  {
    id: "job-4",
    title: "Backend Engineer (Node.js)",
    department: "Engineering",
    location_type: "onsite",
    description: "Build and scale our REST API and data pipeline.",
    skills: ["Node.js", "PostgreSQL", "Redis"],
    status: "paused",
    bond_status: "staked",
    bond_amount: 2800,
    applicant_count: 100,
    created_at: "2026-03-20T10:00:00Z",
    published_at: "2026-03-21T09:00:00Z",
    closed_at: null,
  },
];

const now = new Date("2026-04-17T12:00:00Z");

function hoursFromNow(hours: number): string {
  const d = new Date(now.getTime() + hours * 3600 * 1000);
  return d.toISOString();
}

export const MOCK_CANDIDATES: Candidate[] = [
  {
    id: "c-1",
    name: "Sarah Chen",
    headline: "Senior Frontend Engineer at Stripe",
    location: "San Francisco, CA",
    kyc_status: "verified",
    current_stage: "review",
    review_deadline: hoursFromNow(31.5),
    job_id: "job-1",
    job_title: "Senior Frontend Engineer",
    applied_at: "2026-04-15T14:00:00Z",
    stage_history: [
      { stage: "applied", changed_at: "2026-04-15T14:00:00Z", changed_by: "system" },
      { stage: "review", changed_at: "2026-04-16T09:00:00Z", changed_by: "you@acme.com" },
    ],
    skills: ["React", "TypeScript", "GraphQL", "Next.js"],
    experience: [
      { company: "Stripe", role: "Senior Frontend Engineer", years: 3 },
      { company: "Airbnb", role: "Frontend Engineer", years: 2 },
    ],
  },
  {
    id: "c-2",
    name: "Marcus Williams",
    headline: "Full Stack Engineer at Coinbase",
    location: "New York, NY",
    kyc_status: "verified",
    current_stage: "interview",
    review_deadline: null,
    job_id: "job-1",
    job_title: "Senior Frontend Engineer",
    applied_at: "2026-04-14T10:00:00Z",
    stage_history: [
      { stage: "applied", changed_at: "2026-04-14T10:00:00Z", changed_by: "system" },
      { stage: "review", changed_at: "2026-04-15T08:00:00Z", changed_by: "you@acme.com" },
      { stage: "interview", changed_at: "2026-04-16T11:00:00Z", changed_by: "you@acme.com" },
    ],
    skills: ["React", "Node.js", "Solidity", "TypeScript"],
    experience: [
      { company: "Coinbase", role: "Full Stack Engineer", years: 4 },
    ],
  },
  {
    id: "c-3",
    name: "Priya Patel",
    headline: "Frontend Lead at Vercel",
    location: "Remote",
    kyc_status: "pending",
    current_stage: "applied",
    review_deadline: null,
    job_id: "job-1",
    job_title: "Senior Frontend Engineer",
    applied_at: "2026-04-17T08:00:00Z",
    stage_history: [
      { stage: "applied", changed_at: "2026-04-17T08:00:00Z", changed_by: "system" },
    ],
    skills: ["React", "TypeScript", "Performance"],
    experience: [
      { company: "Vercel", role: "Frontend Lead", years: 2 },
      { company: "Linear", role: "Software Engineer", years: 1 },
    ],
  },
  {
    id: "c-4",
    name: "David Kim",
    headline: "React Developer at Figma",
    location: "Seattle, WA",
    kyc_status: "verified",
    current_stage: "review",
    review_deadline: hoursFromNow(3.2),
    job_id: "job-1",
    job_title: "Senior Frontend Engineer",
    applied_at: "2026-04-15T16:00:00Z",
    stage_history: [
      { stage: "applied", changed_at: "2026-04-15T16:00:00Z", changed_by: "system" },
      { stage: "review", changed_at: "2026-04-15T17:00:00Z", changed_by: "you@acme.com" },
    ],
    skills: ["React", "CSS", "Figma", "Motion"],
    experience: [
      { company: "Figma", role: "React Developer", years: 3 },
    ],
  },
  {
    id: "c-5",
    name: "Alex Torres",
    headline: "Engineering Manager at GitHub",
    location: "Austin, TX",
    kyc_status: "failed",
    current_stage: "rejected",
    review_deadline: null,
    job_id: "job-1",
    job_title: "Senior Frontend Engineer",
    applied_at: "2026-04-13T10:00:00Z",
    stage_history: [
      { stage: "applied", changed_at: "2026-04-13T10:00:00Z", changed_by: "system" },
      { stage: "rejected", changed_at: "2026-04-14T09:00:00Z", changed_by: "you@acme.com" },
    ],
    skills: ["React", "TypeScript"],
    experience: [
      { company: "GitHub", role: "Engineering Manager", years: 5 },
    ],
  },
  {
    id: "c-6",
    name: "Jordan Lee",
    headline: "Solidity Engineer at Uniswap",
    location: "Remote",
    kyc_status: "verified",
    current_stage: "offer",
    review_deadline: null,
    job_id: "job-2",
    job_title: "Solidity Smart Contract Engineer",
    applied_at: "2026-04-10T10:00:00Z",
    stage_history: [
      { stage: "applied", changed_at: "2026-04-10T10:00:00Z", changed_by: "system" },
      { stage: "review", changed_at: "2026-04-11T09:00:00Z", changed_by: "you@acme.com" },
      { stage: "interview", changed_at: "2026-04-13T09:00:00Z", changed_by: "you@acme.com" },
      { stage: "offer", changed_at: "2026-04-16T09:00:00Z", changed_by: "you@acme.com" },
    ],
    skills: ["Solidity", "Foundry", "EVM", "DeFi"],
    experience: [
      { company: "Uniswap", role: "Solidity Engineer", years: 3 },
    ],
  },
  {
    id: "c-7",
    name: "Riley Johnson",
    headline: "Smart Contract Auditor at Trail of Bits",
    location: "Boston, MA",
    kyc_status: "verified",
    current_stage: "review",
    review_deadline: hoursFromNow(-2),
    job_id: "job-2",
    job_title: "Solidity Smart Contract Engineer",
    applied_at: "2026-04-15T10:00:00Z",
    stage_history: [
      { stage: "applied", changed_at: "2026-04-15T10:00:00Z", changed_by: "system" },
      { stage: "review", changed_at: "2026-04-15T12:00:00Z", changed_by: "you@acme.com" },
    ],
    skills: ["Solidity", "Security", "Auditing"],
    experience: [
      { company: "Trail of Bits", role: "Security Researcher", years: 4 },
    ],
  },
];

export const MOCK_WALLET: WalletData = {
  wallet_address: "0x4a3b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b",
  balance: "8400.00",
  transactions: [
    { id: "tx-1", type: "deposit", amount: "5000.00", status: "confirmed", created_at: "2026-04-01T10:00:00Z" },
    { id: "tx-2", type: "bond_locked", amount: "2400.00", status: "confirmed", created_at: "2026-04-02T09:00:00Z" },
    { id: "tx-3", type: "deposit", amount: "10000.00", status: "confirmed", created_at: "2026-04-05T10:00:00Z" },
    { id: "tx-4", type: "bond_locked", amount: "3200.00", status: "confirmed", created_at: "2026-04-06T09:00:00Z" },
    { id: "tx-5", type: "bond_locked", amount: "1000.00", status: "pending", created_at: "2026-04-17T11:00:00Z" },
  ],
  bonds: [
    { job_id: "job-1", job_title: "Senior Frontend Engineer", amount: "2400.00", bond_status: "staked", staked_at: "2026-04-02T09:00:00Z" },
    { job_id: "job-2", job_title: "Solidity Smart Contract Engineer", amount: "3200.00", bond_status: "staked", staked_at: "2026-04-06T09:00:00Z" },
    { job_id: "job-4", job_title: "Backend Engineer (Node.js)", amount: "2800.00", bond_status: "staked", staked_at: "2026-03-21T09:00:00Z" },
  ],
};

export const MOCK_INTERVIEWS: Interview[] = [
  {
    id: "int-1",
    candidate_id: "c-2",
    candidate_name: "Marcus Williams",
    job_title: "Senior Frontend Engineer",
    date: "2026-04-18T14:00:00Z",
    type: "video",
    status: "scheduled",
    notes: "Discuss system design and React architecture.",
  },
  {
    id: "int-2",
    candidate_id: "c-6",
    candidate_name: "Jordan Lee",
    job_title: "Solidity Smart Contract Engineer",
    date: "2026-04-17T16:00:00Z",
    type: "video",
    status: "completed",
    notes: "Strong candidate. Move to offer.",
  },
  {
    id: "int-3",
    candidate_id: "c-4",
    candidate_name: "David Kim",
    job_title: "Senior Frontend Engineer",
    date: "2026-04-19T10:00:00Z",
    type: "phone",
    status: "scheduled",
  },
];

export const SHORTLISTED_IDS = ["c-1", "c-2", "c-6"];
