import { GitHubRawData } from '../../github-adapter/github-data.types';

export const FETCH_DATE = new Date('2024-04-18T12:00:00Z');

export const ALEX_BACKEND: GitHubRawData = {
  fetchedAt: FETCH_DATE,
  profile: {
    username: 'alex-backend',
    accountCreatedAt: new Date('2021-04-18T12:00:00Z'),
    accountAge: 36,
    publicRepos: 8,
    followers: 45,
  },
  repos: [
    {
      name: 'go-core',
      language: 'Go',
      stars: 120,
      forks: 15,
      topics: ['backend', 'go'],
      createdAt: new Date('2021-10-18'),
      pushedAt: new Date('2024-04-10'),
      isFork: false,
      description: 'desc',
    },
    {
      name: 'py-utils',
      language: 'Python',
      stars: 45,
      forks: 5,
      topics: [],
      createdAt: new Date('2022-04-18'),
      pushedAt: new Date('2024-04-12'),
      isFork: false,
      description: 'desc',
    },
    {
      name: 'go-cli',
      language: 'Go',
      stars: 8,
      forks: 1,
      topics: [],
      createdAt: new Date('2022-10-18'),
      pushedAt: new Date('2024-04-15'),
      isFork: false,
      description: 'desc',
    },
    {
      name: 'py-api',
      language: 'Python',
      stars: 0,
      forks: 0,
      topics: [],
      createdAt: new Date('2023-04-18'),
      pushedAt: new Date('2024-04-17'),
      isFork: false,
      description: 'desc',
    },
    {
      name: 'scripts',
      language: 'Shell',
      stars: 200,
      forks: 22,
      topics: ['automation'],
      createdAt: new Date('2023-10-18'),
      pushedAt: new Date('2024-04-18'),
      isFork: false,
      description: 'desc',
    },
    {
      name: 'fork-1',
      language: 'Go',
      stars: 0,
      forks: 0,
      topics: [],
      createdAt: new Date('2021-01-01'),
      pushedAt: new Date('2024-01-01'),
      isFork: true,
      description: 'desc',
    },
    {
      name: 'fork-2',
      language: 'Python',
      stars: 0,
      forks: 0,
      topics: [],
      createdAt: new Date('2021-01-01'),
      pushedAt: new Date('2024-01-01'),
      isFork: true,
      description: 'desc',
    },
    {
      name: 'fork-3',
      language: 'JavaScript',
      stars: 0,
      forks: 0,
      topics: [],
      createdAt: new Date('2021-01-01'),
      pushedAt: new Date('2024-01-01'),
      isFork: true,
      description: 'desc',
    },
  ],
  contributions: {
    weeklyTotals: [...Array(7).fill(0), ...Array(45).fill(10)],
    activeWeeksCount: 45,
  },
  externalPRs: {
    mergedExternalPRCount: 12,
    externalRepoNames: Array(12).fill('external-repo'),
  },
  manifestKeys: {},
};

export const SARAH_FULLSTACK: GitHubRawData = {
  fetchedAt: FETCH_DATE,
  profile: {
    username: 'sarah-fullstack',
    accountCreatedAt: new Date('2022-04-18T12:00:00Z'),
    accountAge: 24,
    publicRepos: 6,
    followers: 20,
  },
  repos: [
    {
      name: 'ts-app',
      language: 'TypeScript',
      stars: 50,
      forks: 10,
      topics: ['react', 'web'],
      createdAt: new Date('2022-10-18'),
      pushedAt: new Date('2024-04-10'),
      isFork: false,
      description: 'desc',
    },
    {
      name: 'ts-lib',
      language: 'TypeScript',
      stars: 30,
      forks: 5,
      topics: ['util'],
      createdAt: new Date('2023-04-18'),
      pushedAt: new Date('2024-04-12'),
      isFork: false,
      description: 'desc',
    },
    {
      name: 'js-game',
      language: 'JavaScript',
      stars: 10,
      forks: 2,
      topics: ['game'],
      createdAt: new Date('2023-10-18'),
      pushedAt: new Date('2024-04-15'),
      isFork: false,
      description: 'desc',
    },
    {
      name: 'styles',
      language: 'CSS',
      stars: 5,
      forks: 1,
      topics: ['ui'],
      createdAt: new Date('2023-12-18'),
      pushedAt: new Date('2024-04-17'),
      isFork: false,
      description: 'desc',
    },
    {
      name: 'fork-1',
      language: 'TypeScript',
      stars: 0,
      forks: 0,
      topics: [],
      createdAt: new Date('2022-01-01'),
      pushedAt: new Date('2024-01-01'),
      isFork: true,
      description: 'desc',
    },
    {
      name: 'fork-2',
      language: 'React',
      stars: 0,
      forks: 0,
      topics: [],
      createdAt: new Date('2022-01-01'),
      pushedAt: new Date('2024-01-01'),
      isFork: true,
      description: 'desc',
    },
  ],
  contributions: {
    weeklyTotals: [...Array(14).fill(0), ...Array(38).fill(8)],
    activeWeeksCount: 38,
  },
  externalPRs: {
    mergedExternalPRCount: 4,
    externalRepoNames: Array(4).fill('external-repo'),
  },
  manifestKeys: {},
};

export const MAYA_DEVOPS: GitHubRawData = {
  fetchedAt: FETCH_DATE,
  profile: {
    username: 'maya-devops',
    accountCreatedAt: new Date('2020-04-18T12:00:00Z'),
    accountAge: 48,
    publicRepos: 3,
    followers: 12,
  },
  repos: [
    {
      name: 'infra-shell',
      language: 'Shell',
      stars: 2,
      forks: 0,
      topics: ['devops'],
      createdAt: new Date('2022-04-18'),
      pushedAt: new Date('2024-04-10'),
      isFork: false,
      description: 'desc',
    },
    {
      name: 'terrafom-hcl',
      language: 'HCL',
      stars: 1,
      forks: 0,
      topics: ['iac'],
      createdAt: new Date('2023-04-18'),
      pushedAt: new Date('2024-04-12'),
      isFork: false,
      description: 'desc',
    },
    {
      name: 'fork-1',
      language: 'Go',
      stars: 0,
      forks: 0,
      topics: [],
      createdAt: new Date('2021-01-01'),
      pushedAt: new Date('2024-01-01'),
      isFork: true,
      description: 'desc',
    },
  ],
  contributions: {
    weeklyTotals: [...Array(12).fill(0), ...Array(40).fill(20)],
    activeWeeksCount: 40,
  },
  externalPRs: {
    mergedExternalPRCount: 2,
    externalRepoNames: ['foo', 'bar'],
  },
  manifestKeys: {},
};

export const NEW_DEV: GitHubRawData = {
  fetchedAt: FETCH_DATE,
  profile: {
    username: 'new-dev',
    accountCreatedAt: new Date('2023-08-18T12:00:00Z'),
    accountAge: 8,
    publicRepos: 5,
    followers: 3,
  },
  repos: [
    {
      name: 'fresh-js',
      language: 'JavaScript',
      stars: 0,
      forks: 0,
      topics: [],
      createdAt: new Date('2024-02-18'),
      pushedAt: new Date('2024-04-10'),
      isFork: false,
      description: 'desc',
    },
    {
      name: 'fork-1',
      language: 'Python',
      stars: 0,
      forks: 0,
      topics: [],
      createdAt: new Date('2023-01-01'),
      pushedAt: new Date('2024-01-01'),
      isFork: true,
      description: 'desc',
    },
    {
      name: 'fork-2',
      language: 'HTML',
      stars: 0,
      forks: 0,
      topics: [],
      createdAt: new Date('2023-01-01'),
      pushedAt: new Date('2024-01-01'),
      isFork: true,
      description: 'desc',
    },
    {
      name: 'fork-3',
      language: 'CSS',
      stars: 0,
      forks: 0,
      topics: [],
      createdAt: new Date('2023-01-01'),
      pushedAt: new Date('2024-01-01'),
      isFork: true,
      description: 'desc',
    },
    {
      name: 'fork-4',
      language: 'JS',
      stars: 0,
      forks: 0,
      topics: [],
      createdAt: new Date('2023-01-01'),
      pushedAt: new Date('2024-01-01'),
      isFork: true,
      description: 'desc',
    },
  ],
  contributions: {
    weeklyTotals: [...Array(37).fill(0), ...Array(15).fill(2)],
    activeWeeksCount: 15,
  },
  externalPRs: {
    mergedExternalPRCount: 0,
    externalRepoNames: [],
  },
  manifestKeys: {},
};

export const GHOST_PROFILE: GitHubRawData = {
  fetchedAt: FETCH_DATE,
  profile: {
    username: 'ghost-profile',
    accountCreatedAt: new Date('2023-02-18T12:00:00Z'),
    accountAge: 14,
    publicRepos: 1,
    followers: 0,
  },
  repos: [
    {
      name: 'one-fork',
      language: 'Java',
      stars: 0,
      forks: 0,
      topics: [],
      createdAt: new Date('2023-01-01'),
      pushedAt: new Date('2024-01-01'),
      isFork: true,
      description: 'desc',
    },
  ],
  contributions: {
    weeklyTotals: [...Array(50).fill(0), 1, 1],
    activeWeeksCount: 2,
  },
  externalPRs: {
    mergedExternalPRCount: 0,
    externalRepoNames: [],
  },
  manifestKeys: {},
};