[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false
seeds     = false

[programs.localnet]
escrow = "4jmvrfqG2Mhx9Wc92NaJvXwzNp2d6xAHFfymz6N3x1Ar"

[programs.devnet]
escrow = "4jmvrfqG2Mhx9Wc92NaJvXwzNp2d6xAHFfymz6N3x1Ar"

# [programs.mainnet]
# escrow = "REPLACE_WITH_YOUR_PROGRAM_ID"

[provider]
cluster = "localnet"
wallet = ".anchor/test-wallet.json"

[test]
startup_wait = 10000

[scripts]
# test = "cargo test"
test = "bash ./scripts/run-anchor-tests.sh"

[hooks]
